language: ruby
cache: bundler

script:
  - bundle exec jekyll build
  #- bundle exec htmlproofer ./_site
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.4
 
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # rou te your build to the container-based infrastructure for a faster build