name: EldarEccor
description: Trying to play with all the shiny new things *.*

repository: EldarEccor/eldareccor.github.io

theme: jekyll-theme-midnight

markdown: kramdown

exclude:
  - vendor
  - README.md